# Usar una imagen base de PHP con Apache
FROM php:8.2-apache

# Copiar los archivos de la aplicación al directorio de trabajo de Apache
COPY . /var/www/html/

# El puerto 80 ya está expuesto por la imagen base de Apache
# EXPOSE 80